import { spawn, spawnSync } from 'node:child_process';
import { openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { paths } from '../config/paths';
import { mergeProcessEnv } from '../platform/spawn';
import {
  ensureLogFiles,
  resolveCliBinPath,
  serviceStderrPath,
  serviceStdoutPath,
  type ServiceStatus,
} from './common';

/**
 * Windows background service **without administrator privileges**.
 *
 * Task Scheduler's `ONLOGON` trigger requires elevation to create (schtasks
 * returns "拒绝访问 / Access denied" from a normal prompt), which is a poor fit
 * for an npm-installed CLI. Instead we use the per-user mechanisms that need no
 * admin:
 *   - **Autostart at logon**: an `HKCU\…\Run` registry value pointing at a
 *     hidden launcher (`wscript` → `.vbs` → `.cmd` → `node … run`). HKCU is
 *     user-writable, so `reg add` needs no elevation; the `.vbs` runs the
 *     console hidden so logon doesn't flash a window.
 *   - **Start now**: a detached, window-hidden `node … run` child.
 *   - **status/stop**: a PID file the bridge writes when launched as the service
 *     (`FEISHU_CODEX_BRIDGE_SERVICE=1`). PID-based liveness is locale-independent
 *     — unlike parsing `schtasks` output, which is localized (中文 Windows prints
 *     「正在运行」, not "Running") and OEM-encoded.
 *
 * Trade-off vs launchd/systemd: the logon trigger has no crash-restart (it only
 * relaunches at the next login) — same limitation the schtasks ONLOGON path had.
 */
const RUN_KEY_PATH = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';
const RUN_KEY_NAME = 'feishu-codex-bridge';
/** Set in the launcher env so a service-launched bridge records its own PID.
 * Exported so the multi-bot supervisor can STRIP it from its children's env —
 * only the supervisor (the actual service process) should own service.pid. */
export const SERVICE_ENV_FLAG = 'FEISHU_CODEX_BRIDGE_SERVICE';

function launcherCmdPath(): string {
  return join(paths.appDir, 'service-launcher.cmd');
}
function launcherVbsPath(): string {
  return join(paths.appDir, 'service-launcher.vbs');
}
function servicePidFile(): string {
  return join(paths.appDir, 'service.pid');
}

/**
 * The `.cmd` the logon launcher runs: bake in PATH (the logon environment is
 * minimal) + the service flag, then run the bridge with logs appended. CRLF
 * because cmd.exe is the interpreter.
 */
export function buildLauncherCmd(): string {
  return [
    '@echo off',
    `set "PATH=${process.env.PATH ?? ''}"`,
    `set "${SERVICE_ENV_FLAG}=1"`,
    `"${process.execPath}" "${resolveCliBinPath()}" run >> "${serviceStdoutPath()}" 2>> "${serviceStderrPath()}"`,
    '',
  ].join('\r\n');
}

/**
 * The `.vbs` the Run key invokes via `wscript`. `WScript.Shell.Run(cmd, 0,
 * False)` runs the `.cmd` with a **hidden** window (style 0) and without
 * waiting, so logon never flashes a console.
 */
export function buildLauncherVbs(): string {
  // VBS escapes a double-quote as "". The Run argument we want is:
  //   cmd /c "<launcherCmdPath>"
  return [
    "' Auto-generated by feishu-codex-bridge. Do not edit.",
    'Set sh = CreateObject("WScript.Shell")',
    `sh.Run "cmd /c ""${launcherCmdPath()}""", 0, False`,
    '',
  ].join('\r\n');
}

/** Launch a detached, window-hidden bridge now; record its PID. */
function startNow(): void {
  const out = openSync(serviceStdoutPath(), 'a');
  const err = openSync(serviceStderrPath(), 'a');
  const child = spawn(process.execPath, [resolveCliBinPath(), 'run'], {
    detached: true,
    windowsHide: true,
    stdio: ['ignore', out, err],
    env: mergeProcessEnv(process.env, { [SERVICE_ENV_FLAG]: '1' }),
  });
  if (child.pid) writeFileSync(servicePidFile(), String(child.pid), 'utf8');
  child.unref();
}

export async function installWinStartup(): Promise<ServiceStatus> {
  await mkdir(paths.appDir, { recursive: true });
  await ensureLogFiles();
  await writeFile(launcherCmdPath(), buildLauncherCmd(), 'utf8');
  await writeFile(launcherVbsPath(), buildLauncherVbs(), 'utf8');

  // HKCU → no admin. Value: wscript.exe "<vbs>" (hidden launcher).
  const reg = spawnSync(
    'reg',
    ['add', RUN_KEY_PATH, '/v', RUN_KEY_NAME, '/t', 'REG_SZ', '/d', `wscript.exe "${launcherVbsPath()}"`, '/f'],
    { encoding: 'utf8' },
  );
  if (reg.status !== 0) {
    throw new Error(`写入登录自启注册表项失败（exit ${reg.status ?? 'unknown'}）：${(reg.stderr || reg.stdout || '').trim()}`);
  }

  startNow();
  return statusWinStartup();
}

export async function uninstallWinStartup(): Promise<void> {
  // Remove autostart (reg delete is fine even if the value is already gone).
  spawnSync('reg', ['delete', RUN_KEY_PATH, '/v', RUN_KEY_NAME, '/f'], { stdio: 'ignore' });
  killService();
  rmSync(servicePidFile(), { force: true });
}

export async function restartWinStartup(): Promise<ServiceStatus> {
  if (!isInstalled()) {
    throw new Error('登录自启未安装（先运行 `feishu-codex-bridge start`）。');
  }
  await ensureLogFiles();
  killService();
  startNow();
  return statusWinStartup();
}

export function statusWinStartup(): ServiceStatus {
  const installed = isInstalled();
  const pid = readServicePid();
  const running = pid !== null && pidAlive(pid);
  return {
    platformName: 'Windows 登录自启（HKCU Run，免管理员）',
    installed,
    running,
    servicePath: `${RUN_KEY_PATH}\\${RUN_KEY_NAME}`,
    stdoutPath: serviceStdoutPath(),
    stderrPath: serviceStderrPath(),
    pid: running && pid !== null ? String(pid) : undefined,
    raw: '',
  };
}

/** Sync run-state check (used by the `daemonRunning` fast path). */
export function winStartupRunning(): boolean {
  const pid = readServicePid();
  return pid !== null && pidAlive(pid);
}

/**
 * Called by `run` at startup: if this process was launched as the background
 * service (env flag set), record its PID so `status`/`stop` can find it — and
 * arrange to clear it on exit. No-op for a foreground `run`.
 */
export function recordServicePid(): void {
  if (process.platform !== 'win32' || !process.env[SERVICE_ENV_FLAG]) return;
  try {
    writeFileSync(servicePidFile(), String(process.pid), 'utf8');
  } catch {
    /* best-effort */
  }
  process.once('exit', clearServicePid);
}

export function clearServicePid(): void {
  if (process.platform !== 'win32' || !process.env[SERVICE_ENV_FLAG]) return;
  try {
    // Only remove the file if it still points at us (avoid racing a restart).
    if (readServicePid() === process.pid) rmSync(servicePidFile(), { force: true });
  } catch {
    /* best-effort */
  }
}

function isInstalled(): boolean {
  const r = spawnSync('reg', ['query', RUN_KEY_PATH, '/v', RUN_KEY_NAME], {
    stdio: ['ignore', 'ignore', 'ignore'],
  });
  return r.status === 0;
}

function readServicePid(): number | null {
  try {
    const pid = Number.parseInt(readFileSync(servicePidFile(), 'utf8').trim(), 10);
    return Number.isFinite(pid) ? pid : null;
  } catch {
    return null;
  }
}

function pidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    // EPERM: the process exists but we may not signal it → still alive.
    return (err as NodeJS.ErrnoException).code === 'EPERM';
  }
}

/** Tree-kill the running service bridge (and its codex children), if any. */
function killService(): void {
  const pid = readServicePid();
  if (pid === null || !pidAlive(pid)) return;
  spawnSync('taskkill', ['/pid', String(pid), '/T', '/F'], { stdio: 'ignore' });
}
