/**
 * Curated re-exports of the codex app-server protocol types.
 *
 * Generated by `codex app-server generate-ts` into ./generated (+ ./generated/v2),
 * pinned to the local codex version. Regenerate via `npm run codex:protocol:update`.
 * Do not hand-edit ./generated/**.
 *
 * Note: v2 emits token-level deltas (AgentMessageDeltaNotification,
 * ReasoningTextDeltaNotification, CommandExecOutputDeltaNotification) in
 * addition to item/started + item/completed — so streaming can be incremental.
 */
export * from './generated/v2';
export type {
  ClientInfo,
  ClientNotification,
  ClientRequest,
  InitializeParams,
  InitializeResponse,
  ServerNotification,
} from './generated';
