package config

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// store.go —— config.json 读写（原子写 + 进程内串行）+ secrets-getter wrapper。
//
// 对齐 TS config/store：
//   - SaveConfig：tmp<pid>-<rand> + 0600 + rename，包级 mutex 串行化同进程并发写。
//   - BuildEncryptedAccountConfig：生成 secret=exec-ref 指向本桥 keystore（明文绝不落 config.json）。
//   - EnsureSecretsGetterWrapper：写 sh wrapper（exec <本二进制> secrets get "$@"），lark-cli 调它解析密钥。

var saveMu sync.Mutex

// LoadConfig 读 config.json；ENOENT 返回零值（视为未配置）。
func LoadConfig(path string) (AppConfig, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return AppConfig{}, nil
		}
		return AppConfig{}, err
	}
	var cfg AppConfig
	if err := json.Unmarshal(b, &cfg); err != nil {
		return AppConfig{}, err
	}
	return cfg, nil
}

// SaveConfig 原子写入 config.json（tmp + 0600 + rename，进程内串行）。
func SaveConfig(path string, cfg AppConfig) error {
	saveMu.Lock()
	defer saveMu.Unlock()
	return writeJSONAtomic(path, cfg, 0o600)
}

func writeJSONAtomic(path string, v any, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	tmp := fmt.Sprintf("%s.tmp-%d-%s", path, os.Getpid(), randHex(4))
	if err := os.WriteFile(tmp, b, perm); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func randHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "00000000"
	}
	return hex.EncodeToString(b)
}

// BuildEncryptedAccountConfig 构造 AppConfig：secret 为 exec-ref 指向本桥 keystore，
// secrets.providers.bridge 指向 secrets-getter wrapper（lark-cli 与本桥共用）。
func BuildEncryptedAccountConfig(appID string, tenant TenantBrand, prefs *AppPreferences) (AppConfig, error) {
	wrapper, err := EnsureSecretsGetterWrapper()
	if err != nil {
		return AppConfig{}, err
	}
	cfg := AppConfig{}
	cfg.Accounts.App = AppCredentials{
		ID:     appID,
		Tenant: tenant,
		Secret: RefSecret(SecretRef{Source: "exec", Provider: "bridge", ID: SecretKeyForApp(appID)}),
	}
	cfg.Secrets = &SecretsConfig{
		Providers: map[string]ProviderConfig{
			"bridge": {Source: "exec", Command: wrapper},
		},
	}
	cfg.Preferences = prefs
	return cfg, nil
}

// EnsureSecretsGetterWrapper 写（覆盖）secrets-getter sh wrapper，指向当前 Go 二进制。
// 0700 权限；每次重写（二进制路径可能变）。
func EnsureSecretsGetterWrapper() (string, error) {
	wrapper := SecretsGetterScript()
	bin, err := os.Executable()
	if err != nil {
		return "", err
	}
	content := "#!/bin/sh\n" +
		"# Auto-generated by feishu-codex-bridge. Do not edit.\n" +
		"exec " + shQuote(bin) + " secrets get \"$@\"\n"
	if err := os.MkdirAll(filepath.Dir(wrapper), 0o755); err != nil {
		return "", err
	}
	tmp := fmt.Sprintf("%s.tmp-%d", wrapper, os.Getpid())
	if err := os.WriteFile(tmp, []byte(content), 0o700); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, wrapper); err != nil {
		return "", err
	}
	return wrapper, nil
}

// shQuote 单引号包裹 s，内部单引号转义（POSIX sh 安全）。
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
